name: Aurionchat
version: ${version}
main: com.mineaurion.aurionchat.bukkit.Bootstrap
authors: [Yann151924]
website: https://mineaurion.com
depend:
  - LuckPerms

commands:
  chat:
    aliases: [ch, channel, aurionchat]
    description: "AurionChat's command to manage chat channels"

permissions:
  aurionchat.chat.colors:
    default: false
    description: Righ to use color in chat
  aurionchat.chat.speak:
    default: false
    description: Right to speak in chat
  aurionchat.reload:
    default: false
    description: Reload connection

